### ISSUE TITLE
MODULE_NOT_FOUND when trying to run `fl2 upgrade 2.0`

### ISSUE THREAD

**Issue by rafaucau** [flarum/cli#45]
`fl2 upgrade 2.0`:

```
 »   ModuleLoadError: [MODULE_NOT_FOUND] require failed to load C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\lib\commands\upgrade\2.0.js: Cannot find module '@flarum/prettier-config/prettierrc.json'
 »   Require stack:
 »   - C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\lib\utils\ast.js
 »   - C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\lib\steps\upgrade\twopointoh\base.js
 »   - C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\lib\steps\upgrade\twopointoh\dependencies.js
 »   - C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\lib\commands\upgrade\2.0.js
 »   - C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\node_modules\@oclif\core\lib\module-loader.js
 »   - C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\node_modules\@oclif\core\lib\config\plugin.js
 »   - C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\node_modules\@oclif\core\lib\config\config.js
 »   - C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\node_modules\@oclif\core\lib\config\index.js
 »   - C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\node_modules\@oclif\core\lib\command.js
 »   - C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\node_modules\@oclif\core\lib\index.js
 »   - C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\bin\run
 »   Code: MODULE_NOT_FOUND
```

Environment:
- Node.js v22.12.0
- NPM 10.9.0
- [Volta](https://volta.sh/) 2.0.1

Flarum CLI installed using `npm install -g @flarum/cli@3`

**Comment by SychO9** [comment]
Looks like prettier is only in devDependencies, I just pushed 3.0.4 (https://github.com/flarum/cli/commit/bc73591972dddaeba622f8cb022f21ae0f002bed) which should fix this, could you try again please?

**Comment by rafaucau** [comment]
Thanks. Now it works.

But there is another problem:
```
  STEP 8/16    Miscellaneous backend changes.

     =>   WORKING.  
Error occurred, and could not complete:
Unexpected token 'D', "
Deprecated"... is not valid JSON
SyntaxError: Unexpected token 'D', "
Deprecated"... is not valid JSON
    at JSON.parse (<anonymous>)
    at PhpSubsystemProvider.handlePhpError (C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\lib\providers\php-provider.js:40:25)
    at PhpSubsystemProvider.run (C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\lib\providers\php-provider.js:34:14)
    at C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\lib\steps\upgrade\twopointoh\backend\misc.js:16:35
    at MiscBackendChanges.applyReplacements (C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\lib\steps\upgrade\twopointoh\base.js:164:34)
    at applyOn (C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\lib\steps\upgrade\twopointoh\base.js:103:47)
    at MiscBackendChanges.run (C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\lib\steps\upgrade\twopointoh\base.js:134:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async StepManager.runStep (C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\lib\boilersmith\step-manager.js:179:23)
    at async checkAndRun (C:\Users\*****\AppData\Local\Volta\tools\image\packages\@flarum\cli\node_modules\@flarum\cli\lib\boilersmith\step-manager.js:92:24)
```

**Comment by SychO9** [comment]
that looks like php deprecation warnings getting in the way 🤦🏼, let me push a fix that turns them off.

**Comment by SychO9** [comment]
I just tagged 3.0.5 to fix that, sorry for the inconvenience, let me know if you face other issues.

**Comment by rafaucau** [comment]
It works now. Thanks
